name: buildx-vce-ml4kids
# Via: https://www.padok.fr/en/blog/multi-architectures-docker-iot
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Push to dockerhub'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Build the images, without pushing
      # When I can build linux/arm64 wheels, add that to build
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7 \
            -t ouvocl/ml4kids:${GITHUB_SHA::7} \
            -f Dockerfile.build .
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Reusing the cache, push the images
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7  \
            -t ouvocl/ml4kids:${GITHUB_SHA::7} \
            -f Dockerfile.build . \
            --push
          docker buildx build \
            --platform linux/amd64,linux/arm/v7  \
            -t ouvocl/ml4kids:latest \
            -f Dockerfile.build . \
            --push

